# Generated by Django 3.2.6 on 2021-08-21 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='car_variation',
        ),
    ]
