# Generated by Django 3.2.6 on 2021-08-21 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_order_car_variation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carvariation',
            name='wheels',
        ),
        migrations.CreateModel(
            name='PlaceOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_on', models.ManyToManyField(to='website.AddOn')),
                ('car_name', models.ManyToManyField(to='website.Car')),
                ('car_variant', models.ManyToManyField(to='website.CarVariation')),
                ('interior', models.ManyToManyField(to='website.Interior')),
                ('paint', models.ManyToManyField(to='website.Paint')),
                ('wheel', models.ManyToManyField(to='website.Wheel')),
            ],
        ),
    ]
