# Generated by Django 3.2.6 on 2021-08-21 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20210821_1554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='car_variation',
        ),
        migrations.AddField(
            model_name='order',
            name='orders',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.placeorder'),
        ),
    ]
