# Generated by Django 3.2.6 on 2021-08-21 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20210821_1633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placeorder',
            name='car_name',
        ),
        migrations.AddField(
            model_name='placeorder',
            name='car_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.car'),
        ),
    ]
