# Generated by Django 3.2.6 on 2021-08-21 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20210821_1738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='add_on',
        ),
        migrations.RemoveField(
            model_name='car',
            name='interior',
        ),
        migrations.RemoveField(
            model_name='car',
            name='paint',
        ),
        migrations.RemoveField(
            model_name='car',
            name='wheel',
        ),
    ]
