# Generated by Django 3.2.6 on 2021-08-21 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_alter_order_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
