# Generated by Django 3.2.6 on 2021-08-21 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_auto_20210821_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placeorder',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
