# Generated by Django 3.2.6 on 2021-08-21 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_alter_placeorder_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placeorder',
            name='car_variant',
        ),
        migrations.AddField(
            model_name='placeorder',
            name='car_variant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.carvariation'),
        ),
    ]
